"""#252 — the collaboration baseline must actually reach the agents.

A policy document that agents never read is decoration. Two things make this
one real, and both are easy to lose silently:

  * `.claude/CLAUDE.md` in this repo is REGENERATED by `instructions.py` on
    every `crew setup` ("fully owned by agent_crew — overwrite entirely"), so a
    rule written only into the checked-in file survives until the next setup and
    then vanishes. It has to live in the generator;
  * there are three protocol templates — tmux, MCP and headless dispatcher —
    and a rule added to one of them silently misses the workers using the other
    two.
"""

import os

import pytest

from agent_crew.instructions import generate

BASELINE_HEADING = "Autonomous Collaboration Baseline"


@pytest.mark.parametrize("delivery", ["tmux", "mcp"])
@pytest.mark.parametrize("role", ["implementer", "reviewer", "tester"])
def test_every_generated_protocol_carries_the_baseline(role, delivery):
    assert BASELINE_HEADING in generate(role, "agent_crew", 8105, delivery=delivery)


def test_the_headless_dispatcher_protocol_carries_it_too(monkeypatch):
    """The dispatcher template is a separate string — the path most likely to
    be forgotten, because it is the one no human ever opens."""
    monkeypatch.setenv("AGENT_CREW_DISPATCHER", "1")

    assert BASELINE_HEADING in generate("implementer", "agent_crew", 8105)


#: Every rule the issue makes binding, with the phrases that must survive an
#: edit. Pinned by CONTENT and per ROLE: the review of PR #254 caught that the
#: first version asserted only a heading and four phrases, so it missed that
#: reviewer and tester never received most of the baseline at all.
BINDING_RULES = {
    "role boundary": ["Alfred", "quota layer"],
    "reversibility": ["irreversible", "restarting live dispatchers"],
    "discovery/proposal/blocker/result": ["discovery", "proposal", "blocker", "result"],
    "no estimate as measurement": ["estimate as a measurement"],
    "cross-bot delegation": ["traceable GitHub issue"],
    "HOLD/VETO/STOP": ["HOLD", "VETO", "STOP"],
    "quota limits": ["quota"],
    "no runaway work": ["recursive delegation", "task explosion"],
    "terminal target": ["already be terminal"],
    "unverifiable -> create nothing": ["cannot verify"],
    "non-reproducing finding": ["does not reproduce"],
    "close with evidence": ["Close with evidence"],
}


@pytest.mark.parametrize("rule,needles", sorted(BINDING_RULES.items()))
@pytest.mark.parametrize("delivery", ["tmux", "mcp"])
@pytest.mark.parametrize("role", ["implementer", "reviewer", "tester"])
def test_every_role_receives_every_binding_rule(role, delivery, rule, needles):
    """★⛔Per role, because the roles do not read the same file.

    Claude Code merges the repo-root `CLAUDE.md` for the implementer, but codex
    reads `AGENTS.md` and gemini reads `GEMINI.md` — neither loads the root
    file. A baseline that lives only there silently binds one role out of
    three, which is what shipped and what the review caught.
    """
    text = generate(role, "agent_crew", 8105, delivery=delivery).lower()

    for needle in needles:
        assert needle.lower() in text, (
            f"{role} ({delivery}) never receives the {rule!r} rule — missing {needle!r}"
        )


@pytest.mark.parametrize("rule,needles", sorted(BINDING_RULES.items()))
def test_the_headless_dispatcher_receives_every_binding_rule(rule, needles, monkeypatch):
    monkeypatch.setenv("AGENT_CREW_DISPATCHER", "1")
    text = generate("implementer", "agent_crew", 8105).lower()

    for needle in needles:
        assert needle.lower() in text, f"dispatcher protocol missing {rule!r}: {needle!r}"


def test_the_block_does_not_delegate_authority_to_a_file_two_roles_cannot_read():
    """⛔The first version said "the full baseline is in the repo-root
    CLAUDE.md". For codex and gemini that sentence pointed at nothing."""
    for role in ("reviewer", "tester"):
        text = generate(role, "agent_crew", 8105)
        assert "BINDING on its own" in text
        assert "The full baseline is in the repo-root" not in text


def test_the_repo_root_instructions_carry_the_full_baseline():
    """The generated blocks are a summary; the root CLAUDE.md is the source."""
    root = os.path.join(os.path.dirname(__file__), "..", "..", "CLAUDE.md")
    text = open(os.path.abspath(root)).read()

    for section in ("Autonomous Collaboration Baseline",
                    "역할 경계",
                    "GitHub = shared blackboard",
                    "HOLD / VETO / STOP",
                    "runaway delegation / review cascade 방지",
                    "policy audit / rollout 연동",
                    "결과는 증거로 닫는다"):
        assert section in text, f"missing baseline section: {section}"


def test_the_cascade_table_states_implementation_status():
    """⛔The mechanism table distinguishes shipped from unshipped on purpose.
    Writing an unmerged guard as if it were in force is exactly the kind of
    false assurance this baseline exists to prevent (#247's lesson)."""
    root = os.path.join(os.path.dirname(__file__), "..", "..", "CLAUDE.md")
    text = open(os.path.abspath(root)).read()

    assert "AGENT_CREW_REVIEW_FIX_MAX_ROUNDS" in text
    assert "✅" in text and "⏳" in text and "❌" in text, \
        "the status column collapsed — shipped and unshipped must stay distinguishable"
