"""#252 — the collaboration baseline must actually reach the agents.

A policy document that agents never read is decoration. Two things make this
one real, and both are easy to lose silently:

  * `.claude/CLAUDE.md` in this repo is REGENERATED by `instructions.py` on
    every `crew setup` ("fully owned by agent_crew — overwrite entirely"), so a
    rule written only into the checked-in file survives until the next setup and
    then vanishes. It has to live in the generator;
  * there are three protocol templates — tmux, MCP and headless dispatcher —
    and a rule added to one of them silently misses the workers using the other
    two.
"""

import os

import pytest

from agent_crew.instructions import generate

BASELINE_HEADING = "Autonomous Collaboration Baseline"


@pytest.mark.parametrize("delivery", ["tmux", "mcp"])
@pytest.mark.parametrize("role", ["implementer", "reviewer", "tester"])
def test_every_generated_protocol_carries_the_baseline(role, delivery):
    assert BASELINE_HEADING in generate(role, "agent_crew", 8105, delivery=delivery)


def test_the_headless_dispatcher_protocol_carries_it_too(monkeypatch):
    """The dispatcher template is a separate string — the path most likely to
    be forgotten, because it is the one no human ever opens."""
    monkeypatch.setenv("AGENT_CREW_DISPATCHER", "1")

    assert BASELINE_HEADING in generate("implementer", "agent_crew", 8105)


@pytest.mark.parametrize("rule", [
    "may already be terminal",      # do not spawn work for a merged/closed PR
    "cannot verify",                # unverifiable → create nothing
    "Escalate rather than act",     # irreversible / outward-facing
    "does not reproduce",           # report, do not re-implement
])
@pytest.mark.parametrize("delivery", ["tmux", "mcp"])
def test_the_load_bearing_rules_are_present_verbatim(rule, delivery):
    """⛔Pinned by content, not just by heading. A heading with the rules edited
    out would pass a presence check and fail the agents."""
    assert rule in generate("implementer", "agent_crew", 8105, delivery=delivery)


def test_the_repo_root_instructions_carry_the_full_baseline():
    """The generated blocks are a summary; the root CLAUDE.md is the source."""
    root = os.path.join(os.path.dirname(__file__), "..", "..", "CLAUDE.md")
    text = open(os.path.abspath(root)).read()

    for section in ("Autonomous Collaboration Baseline",
                    "역할 경계",
                    "GitHub = shared blackboard",
                    "HOLD / VETO / STOP",
                    "runaway delegation / review cascade 방지",
                    "policy audit / rollout 연동",
                    "결과는 증거로 닫는다"):
        assert section in text, f"missing baseline section: {section}"


def test_the_cascade_table_states_implementation_status():
    """⛔The mechanism table distinguishes shipped from unshipped on purpose.
    Writing an unmerged guard as if it were in force is exactly the kind of
    false assurance this baseline exists to prevent (#247's lesson)."""
    root = os.path.join(os.path.dirname(__file__), "..", "..", "CLAUDE.md")
    text = open(os.path.abspath(root)).read()

    assert "AGENT_CREW_REVIEW_FIX_MAX_ROUNDS" in text
    assert "✅" in text and "⏳" in text and "❌" in text, \
        "the status column collapsed — shipped and unshipped must stay distinguishable"
