"""#362 teardown must unregister clean worktrees and preserve unsafe ones."""

import json
import shutil
import subprocess

import pytest
from click.testing import CliRunner

from agent_crew.cli import crew
from agent_crew.instructions import ROLE_FILES


def _git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, check=True, text=True,
                          capture_output=True)


@pytest.fixture
def worktree_project(tmp_path):
    origin = tmp_path / "origin.git"
    repo = tmp_path / "repo"
    worktree = tmp_path / "crew-worktree"
    _git("init", "--bare", str(origin), cwd=tmp_path)
    _git("init", "-b", "main", str(repo), cwd=tmp_path)
    _git("config", "user.email", "crew@example.test", cwd=repo)
    _git("config", "user.name", "Crew Test", cwd=repo)
    (repo / "README").write_text("base\n")
    _git("add", "README", cwd=repo)
    _git("commit", "-m", "base", cwd=repo)
    _git("remote", "add", "origin", str(origin), cwd=repo)
    _git("push", "-u", "origin", "main", cwd=repo)
    _git("worktree", "add", "-b", "agent/crew-test", str(worktree), "main", cwd=repo)
    return repo, worktree


def _state(base, repo, worktree):
    project = "teardown-project"
    project_dir = base / project
    project_dir.mkdir()
    (project_dir / "state.json").write_text(json.dumps({
        "project": project, "session": "unused", "agents": ["claude"],
        "worktrees": {"claude": str(worktree)}, "repo_path": str(repo), "server_pid": 0,
    }))
    return project


def _write_generated_worker_files(worktree):
    """Mirror the untracked protocol files setup leaves in a worktree."""
    for path in {*ROLE_FILES.values(), ".gemini/settings.json", ".mcp.json"}:
        target = worktree / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if path in {"AGENTS.md", "GEMINI.md"}:
            target.write_text("<!-- agent_crew:begin -->\ngenerated\n<!-- agent_crew:end -->\n")
        else:
            target.write_text("generated by agent_crew\n")


def _listed(repo, worktree):
    return str(worktree) in _git("worktree", "list", "--porcelain", cwd=repo).stdout


def test_teardown_removes_clean_worktree_and_registration(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert not worktree.exists()
    assert not _listed(repo, worktree)


def test_teardown_preserves_dirty_worktree_and_reports_command(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    (worktree / "dirty.txt").write_text("do not lose\n")
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert f"git -C {worktree} status --porcelain" in result.output


def test_teardown_ignores_only_untracked_generated_worker_files(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    _write_generated_worker_files(worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert not worktree.exists()
    assert not _listed(repo, worktree)


def test_teardown_preserves_untracked_user_file_among_generated_files(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    _write_generated_worker_files(worktree)
    (worktree / "user-work.txt").write_text("do not lose\n")
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert "uncommitted changes" in result.output


def test_teardown_preserves_user_notes_in_untracked_agents_md(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    (worktree / "AGENTS.md").write_text(
        "<!-- agent_crew:begin -->\ngenerated\n<!-- agent_crew:end -->\n\nMY HAND-WRITTEN NOTES\n"
    )
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and "MY HAND-WRITTEN NOTES" in (worktree / "AGENTS.md").read_text()


@pytest.mark.parametrize(("relative", "content"), [
    (".telegram/.env", "TELEGRAM_BOT_TOKEN=real-developer-token\n"),
    (".gemini/settings.json", '{"mcpServers": {"agent_crew": {}, "MINE": {}}}\n'),
    (".mcp.json", '{"mcpServers": {"agent_crew": {}, "MINE": {}}}\n'),
    (".codex_local/config.toml", "[mcp_servers.agent_crew]\n[mcp_servers.MINE]\n"),
])
def test_teardown_preserves_developer_owned_generated_named_file(
    tmp_path, worktree_project, monkeypatch, relative, content,
):
    """A generated-looking filename never authorizes deleting user content."""
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    target = worktree / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert target.read_text() == content


def test_teardown_accepts_all_setup_generated_config_paths(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    for path in (".telegram/.env", ".codex_local/auth.json", ".codex_local/config.toml"):
        target = worktree / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("generated\n")
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert not worktree.exists() and not _listed(repo, worktree)


def test_teardown_preserves_modified_tracked_protocol_file(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    protocol_file = worktree / ROLE_FILES["implementer"]
    protocol_file.parent.mkdir(parents=True, exist_ok=True)
    protocol_file.write_text("tracked baseline\n")
    _git("add", str(protocol_file.relative_to(worktree)), cwd=worktree)
    _git("commit", "-m", "track protocol file", cwd=worktree)
    protocol_file.write_text("user edit\n")
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert "uncommitted changes" in result.output


def test_teardown_preserves_unpushed_commit_and_reports_command(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    (worktree / "local.txt").write_text("seven commits would be protected too\n")
    _git("add", "local.txt", cwd=worktree)
    _git("commit", "-m", "local only", cwd=worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert f"git -C {worktree} log --oneline HEAD --not --remotes" in result.output


def test_teardown_preserves_staged_change(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    (worktree / "staged.txt").write_text("do not lose\n")
    _git("add", "staged.txt", cwd=worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert "uncommitted changes" in result.output


def test_teardown_preserves_unpublished_detached_head(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    (worktree / "detached.txt").write_text("do not lose\n")
    _git("add", "detached.txt", cwd=worktree)
    _git("commit", "-m", "detached local commit", cwd=worktree)
    _git("checkout", "--detach", cwd=worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code != 0
    assert worktree.exists() and _listed(repo, worktree)
    assert "unpublished commits" in result.output


def test_teardown_prunes_registration_for_already_missing_worktree(tmp_path, worktree_project, monkeypatch):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    shutil.rmtree(worktree)
    assert _listed(repo, worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    result = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert not _listed(repo, worktree)


def test_teardown_discovers_legacy_owner_from_sibling(
    tmp_path, worktree_project, monkeypatch,
):
    repo, worktree = worktree_project
    sibling = tmp_path / "crew-sibling"
    _git("worktree", "add", "-b", "agent/crew-sibling", str(sibling), "main", cwd=repo)
    project = _state(tmp_path, repo, worktree)
    state_path = tmp_path / project / "state.json"
    state = json.loads(state_path.read_text())
    state.pop("repo_path")
    state["worktrees"] = {"missing": str(worktree), "sibling": str(sibling)}
    state_path.write_text(json.dumps(state))
    shutil.rmtree(worktree)
    assert _listed(repo, worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    first = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert first.exit_code == 0, first.output
    assert not _listed(repo, worktree)
    assert not _listed(repo, sibling)


def test_teardown_accepts_legacy_worktree_already_pruned_by_human(
    tmp_path, worktree_project, monkeypatch,
):
    repo, worktree = worktree_project
    sibling = tmp_path / "crew-sibling"
    _git("worktree", "add", "-b", "agent/crew-sibling", str(sibling), "main", cwd=repo)
    project = _state(tmp_path, repo, worktree)
    state_path = tmp_path / project / "state.json"
    state = json.loads(state_path.read_text())
    state.pop("repo_path")
    state["worktrees"] = {"missing": str(worktree), "sibling": str(sibling)}
    state_path.write_text(json.dumps(state))
    shutil.rmtree(worktree)
    _git("worktree", "prune", cwd=repo)
    assert not _listed(repo, worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    retry = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])

    assert retry.exit_code == 0, retry.output
    assert not _listed(repo, sibling)


def test_teardown_unknown_legacy_owner_can_retry_with_reported_repo_path(
    tmp_path, worktree_project, monkeypatch,
):
    repo, worktree = worktree_project
    project = _state(tmp_path, repo, worktree)
    state_path = tmp_path / project / "state.json"
    state = json.loads(state_path.read_text())
    state.pop("repo_path")
    state_path.write_text(json.dumps(state))
    shutil.rmtree(worktree)
    monkeypatch.setattr("agent_crew.cli._tmux_snapshot", lambda _session: "")

    refused = CliRunner().invoke(crew, ["teardown", project, "--base", str(tmp_path)])
    retry = CliRunner().invoke(
        crew, ["teardown", project, "--base", str(tmp_path), "--repo-path", str(repo)],
    )

    assert refused.exit_code != 0
    assert "--repo-path <owning-repository>" in refused.output
    assert retry.exit_code == 0, retry.output
    assert not _listed(repo, worktree)
